In [1]:
import ScraperFC as sfc
import soccerdata as sd
import locale

locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')

Downloading @request dependencies...

Output()

[05/12/26 02:58:47] INFO     No custom team name replacements found. You can configure these in       ]8;id=2291895;file://d:\PROYECTOS_venv\.venv\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=2291896;file://d:\PROYECTOS_venv\.venv\Lib\site-packages\soccerdata\_config.py#92\92]8;;\
                             C:\Users\lucas\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=2291902;file://d:\PROYECTOS_venv\.venv\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=2291903;file://d:\PROYECTOS_venv\.venv\Lib\site-packages\soccerdata\_config.py#190\190]8;;\
                             C:\Users\lucas\soccerdata\config\league_dict.json.

'en_US.UTF-8'

In [2]:
import LanusStats as ls
fbref = ls.Fbref()
df1 = fbref.get_all_player_season_stats('Big 5 European Leagues', '2020-2021')

ModuleNotFoundError: No module named 'undetected_chromedriver'

In [5]:
ls.get_available_season_for_leagues('Fbref','Big 5 European Leagues')

{'id': 'Big5',
 'slug': 'Big-5-European-Leagues',
 'seasons': {'2020-2021', '2021-2022', '2022-2023', '2023-2024', '2024-2025'}}

In [2]:
df1[0]

,Player,stats_Nation,stats_Pos,stats_Squad,stats_Comp,stats_Age,stats_Born,stats_MP,stats_Starts,stats_Min,...,misc_Crs,misc_Int,misc_TklW,misc_PKwon,misc_PKcon,misc_OG,misc_Recov,misc_Won,misc_Lost,misc_Won%
0,Ismael Aaneba,fr FRA,DF,Strasbourg,fr Ligue 1,21,1999,2,0,11,...,0,1,0,0,0,0,0,0,0,0
1,Patrick van Aanholt,nl NED,DF,Crystal Palace,eng Premier League,29,1990,22,20,"1,777",...,40,30,22,0,0,0,136,11,13,45.8
2,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,32,1987,33,33,"2,889",...,0,61,37,0,1,0,200,92,53,63.4
3,Sabit Abdulai,gh GHA,MF,Getafe,es La Liga,21,1999,3,0,60,...,1,0,0,0,0,0,1,1,3,25.0
4,Mehdi Abeid,dz ALG,MF,Nantes,fr Ligue 1,27,1992,18,15,"1,320",...,40,20,19,0,0,0,108,13,18,41.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2817,Steven Zuber,ch SUI,"DF,MF",Eint Frankfurt,de Bundesliga,28,1991,20,6,585,...,31,4,12,0,0,0,49,1,9,10.0
2818,Martín Zubimendi,es ESP,MF,Real Sociedad,es La Liga,21,1999,31,17,"1,882",...,3,40,22,0,0,0,102,47,24,66.2
2819,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,21,1998,14,9,866,...,36,2,3,0,0,0,40,2,13,13.3
2820,Martin Ødegaard,no NOR,MF,Real Madrid,es La Liga,21,1998,7,3,234,...,36,2,3,0,0,0,40,2,13,13.3
2821,Filip Đuričić,rs SRB,"MF,FW",Sassuolo,it Serie A,28,1992,32,27,"2,079",...,12,9,23,0,0,0,90,13,35,27.1

## SCRAPER FC

In [2]:
cap = sfc.Capology()
salaries = cap.scrape_salaries("2023-24", "EPL", "usd")
salaries

Changed currency to usd.

                     EST. BASE SALARY                                     BIO  \
              PLAYER GROSS P/W\n(USD) GROSS P/Y\n(USD) ADJ. GROSS\n(USD) POS.
0    Kevin De Bruyne        $ 536,981     $ 27,923,016      $ 27,923,016    F
1     Erling Haaland        $ 503,420     $ 26,177,828      $ 26,177,828    F
2           Casemiro        $ 469,858     $ 24,432,639      $ 24,432,639    M
3      Mohamed Salah        $ 469,858     $ 24,432,639      $ 24,432,639    F
4     Raphaël Varane        $ 456,434     $ 23,734,564      $ 23,734,564    D
..               ...              ...              ...               ...  ...
605         Hannibal              $ 0              $ 0               $ 0    F
606     João Cancelo              $ 0              $ 0               $ 0    D
607    Andrey Santos              $ 0              $ 0               $ 0    M
608   Máximo Perrone              $ 0              $ 0               $ 0    M
609  Kalvin Phillips              $ 0              $ 0               $ 0    M


    AGE    COUNTRY               CLUB
0    32    Belgium    Manchester City
1    23     Norway    Manchester City
2    31     Brazil  Manchester United
3    31      Egypt          Liverpool
4    30     France  Manchester United
..   ..        ...                ...
605  20    Tunisia  Manchester United
606  29   Portugal    Manchester City
607  19     Brazil            Chelsea
608  20  Argentina    Manchester City
609  28    England    Manchester City

[610 rows x 8 columns]

In [22]:
sd.WhoScored.available_leagues()

['ENG-Premier League',
 'ESP-La Liga',
 'FRA-Ligue 1',
 'GER-Bundesliga',
 'INT-European Championship',
 "INT-Women's World Cup",
 'INT-World Cup',
 'ITA-Serie A']

## SOCCERDATA

In [27]:
ws = sd.WhoScored(leagues="ENG-Premier League", seasons="2024-2025")
epl_schedule = ws.read_schedule()
epl_schedule.head()

[6/14/2025 4:32:51 PM] INFO     Saving cached data to C:\Users\federab\soccerdata\data\WhoScored     ]8;id=743291;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=347749;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\_common.py#263\263]8;;\

[6/14/2025 4:33:55 PM] INFO     Retrieving calendar for ENG-Premier League 2425                    ]8;id=759855;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=630400;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#374\374]8;;\

[6/14/2025 4:34:04 PM] INFO     [1/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=927337;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=69923;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:12 PM] INFO     [2/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=930864;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=107460;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:21 PM] INFO     [3/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=320403;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=476018;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:27 PM] INFO     [4/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=578568;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=671582;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:36 PM] INFO     [5/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=653971;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=120396;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:42 PM] INFO     [6/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=280544;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=969775;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:51 PM] INFO     [7/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=856849;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=637868;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:34:59 PM] INFO     [8/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=895749;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=623085;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:35:05 PM] INFO     [9/10] Retrieving fixtures for ENG-Premier League 2425             ]8;id=17376;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=963179;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

[6/14/2025 4:35:15 PM] INFO     [10/10] Retrieving fixtures for ENG-Premier League 2425            ]8;id=601995;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py\whoscored.py]8;;\:]8;id=301811;file://c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\soccerdata\whoscored.py#403\403]8;;\

                                                               stage_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham     23400
                          2024-08-17 Arsenal-Wolves               23400
                          2024-08-17 Everton-Brighton             23400
                          2024-08-17 Ipswich-Liverpool            23400
                          2024-08-17 Newcastle-Southampton        23400

                                                               game_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham  1821049
                          2024-08-17 Arsenal-Wolves            1821052
                          2024-08-17 Everton-Brighton          1821054
                          2024-08-17 Ipswich-Liverpool         1821050
                          2024-08-17 Newcastle-Southampton     1821055

                                                               status  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham       6
                          2024-08-17 Arsenal-Wolves                 6
                          2024-08-17 Everton-Brighton               6
                          2024-08-17 Ipswich-Liverpool              6
                          2024-08-17 Newcastle-Southampton          6

                                                                        start_time  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham  2024-08-16T20:00:00
                          2024-08-17 Arsenal-Wolves            2024-08-17T15:00:00
                          2024-08-17 Everton-Brighton          2024-08-17T15:00:00
                          2024-08-17 Ipswich-Liverpool         2024-08-17T12:30:00
                          2024-08-17 Newcastle-Southampton     2024-08-17T15:00:00

                                                               home_team_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham            32
                          2024-08-17 Arsenal-Wolves                      13
                          2024-08-17 Everton-Brighton                    31
                          2024-08-17 Ipswich-Liverpool                  165
                          2024-08-17 Newcastle-Southampton               23

                                                                       home_team  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham  Manchester United
                          2024-08-17 Arsenal-Wolves                      Arsenal
                          2024-08-17 Everton-Brighton                    Everton
                          2024-08-17 Ipswich-Liverpool                   Ipswich
                          2024-08-17 Newcastle-Southampton             Newcastle

                                                               home_yellow_cards  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                  2
                          2024-08-17 Arsenal-Wolves                            2
                          2024-08-17 Everton-Brighton                          1
                          2024-08-17 Ipswich-Liverpool                         3
                          2024-08-17 Newcastle-Southampton                     2

                                                               home_red_cards  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham               0
                          2024-08-17 Arsenal-Wolves                         0
                          2024-08-17 Everton-Brighton                       1
                          2024-08-17 Ipswich-Liverpool                      0
                          2024-08-17 Newcastle-Southampton                  1

                                                               away_team_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham           170
                          2024-08-17 Arsenal-Wolves                     161
                          2024-08-17 Everton-Brighton                   211
                          2024-08-17 Ipswich-Liverpool                   26
                          2024-08-17 Newcastle-Southampton               18

                                                                 away_team  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham       Fulham
                          2024-08-17 Arsenal-Wolves                 Wolves
                          2024-08-17 Everton-Brighton             Brighton
                          2024-08-17 Ipswich-Liverpool           Liverpool
                          2024-08-17 Newcastle-Southampton     Southampton

                                                               ...  period  \
league             season game                                 ...
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham  ...       7
                          2024-08-17 Arsenal-Wolves            ...       7
                          2024-08-17 Everton-Brighton          ...       7
                          2024-08-17 Ipswich-Liverpool         ...       7
                          2024-08-17 Newcastle-Southampton     ...       7

                                                               extra_result_field  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                None
                          2024-08-17 Arsenal-Wolves                          None
                          2024-08-17 Everton-Brighton                        None
                          2024-08-17 Ipswich-Liverpool                       None
                          2024-08-17 Newcastle-Southampton                   None

                                                               home_extratime_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                  None
                          2024-08-17 Arsenal-Wolves                            None
                          2024-08-17 Everton-Brighton                          None
                          2024-08-17 Ipswich-Liverpool                         None
                          2024-08-17 Newcastle-Southampton                     None

                                                               away_extratime_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                  None
                          2024-08-17 Arsenal-Wolves                            None
                          2024-08-17 Everton-Brighton                          None
                          2024-08-17 Ipswich-Liverpool                         None
                          2024-08-17 Newcastle-Southampton                     None

                                                              home_penalty_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham               None
                          2024-08-17 Arsenal-Wolves                         None
                          2024-08-17 Everton-Brighton                       None
                          2024-08-17 Ipswich-Liverpool                      None
                          2024-08-17 Newcastle-Southampton                  None

                                                              away_penalty_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham               None
                          2024-08-17 Arsenal-Wolves                         None
                          2024-08-17 Everton-Brighton                       None
                          2024-08-17 Ipswich-Liverpool                      None
                          2024-08-17 Newcastle-Southampton                  None

                                                                     started_at_utc  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham  2024-08-16T19:00:31Z
                          2024-08-17 Arsenal-Wolves            2024-08-17T14:00:36Z
                          2024-08-17 Everton-Brighton          2024-08-17T14:00:43Z
                          2024-08-17 Ipswich-Liverpool         2024-08-17T11:31:17Z
                          2024-08-17 Newcastle-Southampton     2024-08-17T14:01:14Z

                                                               first_half_ended_at_utc  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham     2024-08-16T19:46:31Z
                          2024-08-17 Arsenal-Wolves               2024-08-17T14:46:47Z
                          2024-08-17 Everton-Brighton             2024-08-17T14:49:48Z
                          2024-08-17 Ipswich-Liverpool            2024-08-17T12:17:21Z
                          2024-08-17 Newcastle-Southampton        2024-08-17T14:50:07Z

                                                              second_half_started_at_utc  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham       2024-08-16T20:02:38Z
                          2024-08-17 Arsenal-Wolves                 2024-08-17T15:02:32Z
                          2024-08-17 Everton-Brighton               2024-08-17T15:05:55Z
                          2024-08-17 Ipswich-Liverpool              2024-08-17T12:33:48Z
                          2024-08-17 Newcastle-Southampton          2024-08-17T15:06:06Z

                                                              stage
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham  None
                          2024-08-17 Arsenal-Wolves            None
                          2024-08-17 Everton-Brighton          None
                          2024-08-17 Ipswich-Liverpool         None
                          2024-08-17 Newcastle-Southampton     None

[5 rows x 43 columns]

In [28]:
epl_schedule

                                                                stage_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham      23400
                          2024-08-17 Arsenal-Wolves                23400
                          2024-08-17 Everton-Brighton              23400
                          2024-08-17 Ipswich-Liverpool             23400
                          2024-08-17 Newcastle-Southampton         23400
...                                                                  ...
                          2025-05-25 Newcastle-Everton             23400
                          2025-05-25 Nottingham Forest-Chelsea     23400
                          2025-05-25 Southampton-Arsenal           23400
                          2025-05-25 Tottenham-Brighton            23400
                          2025-05-25 Wolves-Brentford              23400

                                                                game_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham   1821049
                          2024-08-17 Arsenal-Wolves             1821052
                          2024-08-17 Everton-Brighton           1821054
                          2024-08-17 Ipswich-Liverpool          1821050
                          2024-08-17 Newcastle-Southampton      1821055
...                                                                 ...
                          2025-05-25 Newcastle-Everton          1821336
                          2025-05-25 Nottingham Forest-Chelsea  1821339
                          2025-05-25 Southampton-Arsenal        1821342
                          2025-05-25 Tottenham-Brighton         1821345
                          2025-05-25 Wolves-Brentford           1821348

                                                                status  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham        6
                          2024-08-17 Arsenal-Wolves                  6
                          2024-08-17 Everton-Brighton                6
                          2024-08-17 Ipswich-Liverpool               6
                          2024-08-17 Newcastle-Southampton           6
...                                                                ...
                          2025-05-25 Newcastle-Everton               6
                          2025-05-25 Nottingham Forest-Chelsea       6
                          2025-05-25 Southampton-Arsenal             6
                          2025-05-25 Tottenham-Brighton              6
                          2025-05-25 Wolves-Brentford                6

                                                                         start_time  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham   2024-08-16T20:00:00
                          2024-08-17 Arsenal-Wolves             2024-08-17T15:00:00
                          2024-08-17 Everton-Brighton           2024-08-17T15:00:00
                          2024-08-17 Ipswich-Liverpool          2024-08-17T12:30:00
                          2024-08-17 Newcastle-Southampton      2024-08-17T15:00:00
...                                                                             ...
                          2025-05-25 Newcastle-Everton          2025-05-25T16:00:00
                          2025-05-25 Nottingham Forest-Chelsea  2025-05-25T16:00:00
                          2025-05-25 Southampton-Arsenal        2025-05-25T16:00:00
                          2025-05-25 Tottenham-Brighton         2025-05-25T16:00:00
                          2025-05-25 Wolves-Brentford           2025-05-25T16:00:00

                                                                home_team_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham             32
                          2024-08-17 Arsenal-Wolves                       13
                          2024-08-17 Everton-Brighton                     31
                          2024-08-17 Ipswich-Liverpool                   165
                          2024-08-17 Newcastle-Southampton                23
...                                                                      ...
                          2025-05-25 Newcastle-Everton                    23
                          2025-05-25 Nottingham Forest-Chelsea           174
                          2025-05-25 Southampton-Arsenal                  18
                          2025-05-25 Tottenham-Brighton                   30
                          2025-05-25 Wolves-Brentford                    161

                                                                        home_team  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham   Manchester United
                          2024-08-17 Arsenal-Wolves                       Arsenal
                          2024-08-17 Everton-Brighton                     Everton
                          2024-08-17 Ipswich-Liverpool                    Ipswich
                          2024-08-17 Newcastle-Southampton              Newcastle
...                                                                           ...
                          2025-05-25 Newcastle-Everton                  Newcastle
                          2025-05-25 Nottingham Forest-Chelsea  Nottingham Forest
                          2025-05-25 Southampton-Arsenal              Southampton
                          2025-05-25 Tottenham-Brighton                 Tottenham
                          2025-05-25 Wolves-Brentford                      Wolves

                                                                home_yellow_cards  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   2
                          2024-08-17 Arsenal-Wolves                             2
                          2024-08-17 Everton-Brighton                           1
                          2024-08-17 Ipswich-Liverpool                          3
                          2024-08-17 Newcastle-Southampton                      2
...                                                                           ...
                          2025-05-25 Newcastle-Everton                          1
                          2025-05-25 Nottingham Forest-Chelsea                  2
                          2025-05-25 Southampton-Arsenal                        0
                          2025-05-25 Tottenham-Brighton                         3
                          2025-05-25 Wolves-Brentford                           2

                                                                home_red_cards  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                0
                          2024-08-17 Arsenal-Wolves                          0
                          2024-08-17 Everton-Brighton                        1
                          2024-08-17 Ipswich-Liverpool                       0
                          2024-08-17 Newcastle-Southampton                   1
...                                                                        ...
                          2025-05-25 Newcastle-Everton                       0
                          2025-05-25 Nottingham Forest-Chelsea               0
                          2025-05-25 Southampton-Arsenal                     0
                          2025-05-25 Tottenham-Brighton                      0
                          2025-05-25 Wolves-Brentford                        0

                                                                away_team_id  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham            170
                          2024-08-17 Arsenal-Wolves                      161
                          2024-08-17 Everton-Brighton                    211
                          2024-08-17 Ipswich-Liverpool                    26
                          2024-08-17 Newcastle-Southampton                18
...                                                                      ...
                          2025-05-25 Newcastle-Everton                    31
                          2025-05-25 Nottingham Forest-Chelsea            15
                          2025-05-25 Southampton-Arsenal                  13
                          2025-05-25 Tottenham-Brighton                  211
                          2025-05-25 Wolves-Brentford                    189

                                                                  away_team  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham        Fulham
                          2024-08-17 Arsenal-Wolves                  Wolves
                          2024-08-17 Everton-Brighton              Brighton
                          2024-08-17 Ipswich-Liverpool            Liverpool
                          2024-08-17 Newcastle-Southampton      Southampton
...                                                                     ...
                          2025-05-25 Newcastle-Everton              Everton
                          2025-05-25 Nottingham Forest-Chelsea      Chelsea
                          2025-05-25 Southampton-Arsenal            Arsenal
                          2025-05-25 Tottenham-Brighton            Brighton
                          2025-05-25 Wolves-Brentford             Brentford

                                                                ...  period  \
league             season game                                  ...
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham   ...       7
                          2024-08-17 Arsenal-Wolves             ...       7
                          2024-08-17 Everton-Brighton           ...       7
                          2024-08-17 Ipswich-Liverpool          ...       7
                          2024-08-17 Newcastle-Southampton      ...       7
...                                                             ...     ...
                          2025-05-25 Newcastle-Everton          ...       7
                          2025-05-25 Nottingham Forest-Chelsea  ...       7
                          2025-05-25 Southampton-Arsenal        ...       7
                          2025-05-25 Tottenham-Brighton         ...       7
                          2025-05-25 Wolves-Brentford           ...       7

                                                                extra_result_field  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                 None
                          2024-08-17 Arsenal-Wolves                           None
                          2024-08-17 Everton-Brighton                         None
                          2024-08-17 Ipswich-Liverpool                        None
                          2024-08-17 Newcastle-Southampton                    None
...                                                                            ...
                          2025-05-25 Newcastle-Everton                        None
                          2025-05-25 Nottingham Forest-Chelsea                None
                          2025-05-25 Southampton-Arsenal                      None
                          2025-05-25 Tottenham-Brighton                       None
                          2025-05-25 Wolves-Brentford                         None

                                                                home_extratime_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   None
                          2024-08-17 Arsenal-Wolves                             None
                          2024-08-17 Everton-Brighton                           None
                          2024-08-17 Ipswich-Liverpool                          None
                          2024-08-17 Newcastle-Southampton                      None
...                                                                              ...
                          2025-05-25 Newcastle-Everton                          None
                          2025-05-25 Nottingham Forest-Chelsea                  None
                          2025-05-25 Southampton-Arsenal                        None
                          2025-05-25 Tottenham-Brighton                         None
                          2025-05-25 Wolves-Brentford                           None

                                                                away_extratime_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                   None
                          2024-08-17 Arsenal-Wolves                             None
                          2024-08-17 Everton-Brighton                           None
                          2024-08-17 Ipswich-Liverpool                          None
                          2024-08-17 Newcastle-Southampton                      None
...                                                                              ...
                          2025-05-25 Newcastle-Everton                          None
                          2025-05-25 Nottingham Forest-Chelsea                  None
                          2025-05-25 Southampton-Arsenal                        None
                          2025-05-25 Tottenham-Brighton                         None
                          2025-05-25 Wolves-Brentford                           None

                                                               home_penalty_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                None
                          2024-08-17 Arsenal-Wolves                          None
                          2024-08-17 Everton-Brighton                        None
                          2024-08-17 Ipswich-Liverpool                       None
                          2024-08-17 Newcastle-Southampton                   None
...                                                                           ...
                          2025-05-25 Newcastle-Everton                       None
                          2025-05-25 Nottingham Forest-Chelsea               None
                          2025-05-25 Southampton-Arsenal                     None
                          2025-05-25 Tottenham-Brighton                      None
                          2025-05-25 Wolves-Brentford                        None

                                                               away_penalty_score  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham                None
                          2024-08-17 Arsenal-Wolves                          None
                          2024-08-17 Everton-Brighton                        None
                          2024-08-17 Ipswich-Liverpool                       None
                          2024-08-17 Newcastle-Southampton                   None
...                                                                           ...
                          2025-05-25 Newcastle-Everton                       None
                          2025-05-25 Nottingham Forest-Chelsea               None
                          2025-05-25 Southampton-Arsenal                     None
                          2025-05-25 Tottenham-Brighton                      None
                          2025-05-25 Wolves-Brentford                        None

                                                                      started_at_utc  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham   2024-08-16T19:00:31Z
                          2024-08-17 Arsenal-Wolves             2024-08-17T14:00:36Z
                          2024-08-17 Everton-Brighton           2024-08-17T14:00:43Z
                          2024-08-17 Ipswich-Liverpool          2024-08-17T11:31:17Z
                          2024-08-17 Newcastle-Southampton      2024-08-17T14:01:14Z
...                                                                              ...
                          2025-05-25 Newcastle-Everton          2025-05-25T15:00:39Z
                          2025-05-25 Nottingham Forest-Chelsea  2025-05-25T15:01:35Z
                          2025-05-25 Southampton-Arsenal        2025-05-25T15:00:16Z
                          2025-05-25 Tottenham-Brighton         2025-05-25T15:00:42Z
                          2025-05-25 Wolves-Brentford           2025-05-25T15:00:18Z

                                                                first_half_ended_at_utc  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham      2024-08-16T19:46:31Z
                          2024-08-17 Arsenal-Wolves                2024-08-17T14:46:47Z
                          2024-08-17 Everton-Brighton              2024-08-17T14:49:48Z
                          2024-08-17 Ipswich-Liverpool             2024-08-17T12:17:21Z
                          2024-08-17 Newcastle-Southampton         2024-08-17T14:50:07Z
...                                                                                 ...
                          2025-05-25 Newcastle-Everton             2025-05-25T15:46:42Z
                          2025-05-25 Nottingham Forest-Chelsea     2025-05-25T15:47:39Z
                          2025-05-25 Southampton-Arsenal           2025-05-25T15:46:28Z
                          2025-05-25 Tottenham-Brighton            2025-05-25T15:47:16Z
                          2025-05-25 Wolves-Brentford              2025-05-25T15:46:47Z

                                                               second_half_started_at_utc  \
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham        2024-08-16T20:02:38Z
                          2024-08-17 Arsenal-Wolves                  2024-08-17T15:02:32Z
                          2024-08-17 Everton-Brighton                2024-08-17T15:05:55Z
                          2024-08-17 Ipswich-Liverpool               2024-08-17T12:33:48Z
                          2024-08-17 Newcastle-Southampton           2024-08-17T15:06:06Z
...                                                                                   ...
                          2025-05-25 Newcastle-Everton               2025-05-25T16:07:22Z
                          2025-05-25 Nottingham Forest-Chelsea       2025-05-25T16:07:15Z
                          2025-05-25 Southampton-Arsenal             2025-05-25T16:01:59Z
                          2025-05-25 Tottenham-Brighton              2025-05-25T16:04:00Z
                          2025-05-25 Wolves-Brentford                2025-05-25T16:03:17Z

                                                               stage
league             season game
ENG-Premier League 2425   2024-08-16 Manchester United-Fulham   None
                          2024-08-17 Arsenal-Wolves             None
                          2024-08-17 Everton-Brighton           None
                          2024-08-17 Ipswich-Liverpool          None
                          2024-08-17 Newcastle-Southampton      None
...                                                              ...
                          2025-05-25 Newcastle-Everton          None
                          2025-05-25 Nottingham Forest-Chelsea  None
                          2025-05-25 Southampton-Arsenal        None
                          2025-05-25 Tottenham-Brighton         None
                          2025-05-25 Wolves-Brentford           None

[380 rows x 43 columns]

## LANUSSTATS

In [29]:
ls.get_available_pages()

dict_keys(['Fbref', 'Sofascore', '365Scores', 'Fotmob', 'Transfermarkt', 'DataFactory'])

In [30]:
ls.get_available_leagues("Fbref")

['Copa de la Liga',
 'Primera Division Argentina',
 'Primera Division Uruguay',
 'Brasileirao',
 'Brasileirao B',
 'Primera Division Colombia',
 'Primera Division Chile',
 'Primera Division Peru',
 'Primera Division Venezuela',
 'Primera Division Ecuador',
 'Primera Division Bolivia',
 'Primera Division Paraguay',
 'Brasileirao F',
 'MLS',
 'USL Championship',
 'Premier League',
 'La Liga',
 'Ligue 1',
 'Bundesliga',
 'Serie A',
 'Big 5 European Leagues',
 'Danish Superliga',
 'Eredivise',
 'Primeira Liga Portugal',
 'Copa America',
 'Euros',
 'Saudi League',
 'EFL Championship',
 'La Liga 2',
 'Belgian Pro League',
 'Challenger Pro League',
 '2. Bundesliga',
 'Ligue 2',
 'Serie B',
 'J1 League',
 'NSWL',
 'Wowens Super League',
 'Liga F',
 'Premier Division South Africa',
 'Champions League',
 'Europa League',
 'Conference League',
 'Copa Libertadores',
 'Liga MX']

In [34]:
ls.get_available_season_for_leagues("Fbref", "Brasileirao")

{'id': 24,
 'slug': 'Serie-A',
 'seasons': {'2021', '2022', '2023', '2024', '2025'}}

In [ ]:
fbref = ls.Fbref()
fbref.get_player_season_stats('gca', 'Brasileirao', "2025", save_csv=False, add_page_name=False)

Starting to scrape player data from Fbref...

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,SCA,SCA90,...,Fld,Def,GCA,GCA90,PassLive,PassDead,TO,Sh,Fld,Def
0,Abner,br BRA,DF,Juventude,Brasileirao,21-056,2004,5.5,1,0.18,...,0,0,1,0.18,1,0,0,0,0,0
1,Nicolás Acevedo,uy URU,"MF,DF",Bahia,Brasileirao,26-061,1999,3.3,2,0.60,...,0,0,1,0.30,1,0,0,0,0,0
2,Adson,br BRA,"FW,MF",Vasco da Gama,Brasileirao,24-251,2000,2.3,10,4.29,...,0,0,0,0.00,0,0,0,0,0,0
3,Braian Aguirre,ar ARG,DF,Internacional,Brasileirao,24-321,2000,10.9,16,1.47,...,0,1,0,0.00,0,0,0,0,0,0
4,Carlos Alberto,br BRA,"FW,MF",Sport Recife,Brasileirao,23-061,2002,3.7,9,2.45,...,0,1,0,0.00,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,Mateus Xavier,br BRA,"FW,MF",Santos,Brasileirao,17-350,2007,0.4,0,0.00,...,0,0,0,0.00,0,0,0,0,0,0
541,Samuel Xavier,br BRA,DF,Fluminense,Brasileirao,35-008,1990,8.2,19,2.30,...,1,0,2,0.24,2,0,0,0,0,0
542,Yago,br BRA,MF,Mirassol,Brasileirao,30-131,1995,4.1,9,2.19,...,1,0,0,0.00,0,0,0,0,0,0
543,Yago,br BRA,MF,Internacional,Brasileirao,18-129,2007,0.8,4,4.93,...,0,0,0,0.00,0,0,0,0,0,0
544,Lukas Zuccarello,br BRA,FW,Vasco da Gama,Brasileirao,18-194,2006,0.3,1,3.75,...,0,0,0,0.00,0,0,0,0,0,0